stages:
  - lint
  - test
  - build

# Linting stage
lint:
  stage: lint
  image: oven/bun:latest  # Use the official Bun Docker image
  script:
    - bun install          # Install dependencies
    - bun run ui:lint      # Run your linting command (update if necessary)
  only:
    - main  # Run this job only on the main branch

# Testing stage
test:
  stage: test
  image: oven/bun:latest  # Use the official Bun Docker image
  script:
    - bun install          # Install dependencies
    - |
      if bun run ui:test; then
        echo "Tests ran successfully.";
      else
        echo "No test script defined in package.json.";
      fi
  only:
    - main  # Run this job only on the main branch

# Build and serve stage
build:
  stage: build
  image: oven/bun:latest  # Use the official Bun Docker image
  script:
    - bun install          # Install dependencies
    - bun run ui:install   # Install UI dependencies
    - bun run ui:build     # Build the Vite + React app
    - echo "Successfully built the application"  # Placeholder message
  only:
    - main  # Run this job only on the main branch

# Deploy stage (optional)
# deploy:
#   stage: deploy
#   image: oven/bun:latest
#   script:
#     - docker build -t your-image-name . # Build your Docker image
#     - docker run -d -p 3000:3000 your-image-name # Run your Docker container
#   only:
#     - main
